### PR TITLE
L5 & 5.1 Implementation

### PR DESCRIPTION
**Pull request by petermein**
Fixed the package for use with Laravel 5 and 5.1

### CODE REVIEW

**Comment by petermein** [comment]
It seems the repo is no longer maintained.

**Comment by davibennun** [comment]
Hi Peter, sorry for the delayed answer. 
Since this wrapper is still using the development branch, updating it to L5 would break 4.2 installations.
I suggest to create another branch just for L5, or set up a new repo just for L5 with a stable release.

**Comment by petermein** [comment]
A new branch for 5.0 and 5.1 seems like the best option. Else there are two repo's with the same namespace. Maybe you can pull this to a new branch and then edit the readme to explain the different branches?

**Comment by davibennun** [comment]
Just created a laravel5 branch using your fork, thanks!

**Pull request closed without merging**
